<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [2]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [3]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))


In [4]:

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
# ========
print(a.ndim, a.shape, a.size, len(a))
print(b.ndim, b.shape)

2 (100, 100) 10000 100
2 (100, 100)


In [5]:
def mult(a, b):
    """  
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy
    """
    c = np.zeros((len(a), len(a[0])))

    for i in range(len(a)):
        # iterate through columns of Y
        for j in range(len(b[0])):
            # iterate through rows of Y
            for k in range(len(b)):
                c[i][j] += a[i][k] * b[k][j]


    return c.tolist()

In [6]:
def np_mult(a, b):
    """  
    a: np.array[size, size]             --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    #return a @ b
    return np.dot(a, b).tolist()

In [7]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)
print(type(M1))
M1

<class 'list'>
CPU times: user 772 ms, sys: 3.98 ms, total: 776 ms
Wall time: 777 ms


[[23.02254845215889,
  19.998288310719083,
  22.932416059107986,
  23.62210121930635,
  20.409793128042182,
  22.584990035701253,
  20.01865711938648,
  23.38731737779853,
  21.985351011944225,
  22.09627065362282,
  21.918920315772066,
  22.731141299248954,
  21.087807042199508,
  19.922492122018827,
  20.191543685683442,
  22.087662491943817,
  22.906798787596397,
  23.879489583958733,
  19.962869037051128,
  21.046868588309568,
  22.917300734061527,
  22.340441057252164,
  22.851673992401597,
  20.687028634694,
  21.58827096990182,
  20.910670302449752,
  24.678792848625974,
  21.097143149006758,
  24.088227877648364,
  22.062315316027245,
  22.192085857788765,
  19.966299161823837,
  21.841632875323768,
  20.079744988440446,
  22.499983847976456,
  19.78490529507274,
  18.50426812320889,
  22.27631308858694,
  22.155201567980185,
  24.26204899492065,
  22.56602153430048,
  21.27683818940234,
  21.45806487405613,
  22.690134904426817,
  21.406306560508384,
  19.76405918127488,
  22.

In [8]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)
print(type(M2))
M2

<class 'list'>
CPU times: user 4.47 ms, sys: 1.06 ms, total: 5.53 ms
Wall time: 1.28 ms


[[23.02254845215889,
  19.998288310719083,
  22.93241605910799,
  23.62210121930635,
  20.409793128042185,
  22.58499003570125,
  20.018657119386475,
  23.387317377798528,
  21.98535101194422,
  22.09627065362282,
  21.918920315772066,
  22.731141299248954,
  21.087807042199508,
  19.92249212201883,
  20.191543685683442,
  22.087662491943817,
  22.906798787596397,
  23.87948958395873,
  19.96286903705113,
  21.046868588309568,
  22.917300734061524,
  22.340441057252164,
  22.851673992401597,
  20.687028634693995,
  21.58827096990182,
  20.910670302449752,
  24.67879284862597,
  21.097143149006758,
  24.088227877648364,
  22.062315316027245,
  22.19208585778876,
  19.966299161823837,
  21.841632875323768,
  20.079744988440446,
  22.499983847976456,
  19.784905295072736,
  18.50426812320889,
  22.27631308858694,
  22.155201567980185,
  24.262048994920647,
  22.56602153430048,
  21.27683818940234,
  21.45806487405613,
  22.690134904426817,
  21.406306560508384,
  19.76405918127488,
  22.5

In [9]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [10]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.61077314 0.65274418 0.58898039] [0.00313027 0.53092735 0.00894298]


In [11]:
def scalar_product(a, b):
    """  
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """ 
    c = 0

    for i in range(len(a)):
        c += a[i]*b[i]
    
    return c


In [12]:
def np_scalar_product(a,b):
    """  
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """ 
    return np.dot(a, b)

In [13]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

CPU times: user 10 µs, sys: 3 µs, total: 13 µs
Wall time: 17.4 µs
CPU times: user 36 µs, sys: 10 µs, total: 46 µs
Wall time: 51.3 µs


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [14]:
def np_diag_2k(a):
    """  
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    diag = np.diag(a)
    return diag[diag % 2 == 0].sum()

In [15]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[1, 5, 9, 2, 3],
       [4, 1, 8, 3, 2],
       [4, 2, 6, 7, 3],
       [1, 1, 2, 1, 8],
       [6, 7, 5, 4, 9]])

In [16]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 53 µs, sys: 16 µs, total: 69 µs
Wall time: 72.7 µs


6

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​ 

In [17]:
def cumsum(a):
    """  
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает 
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность 
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    c = [0]*len(a)
    for i in range(len(a)):
        c[i]=a[i].cumsum()

    return c


In [18]:
# зададим некоторую последовательность и проверим ее на вашей функции. 
# A = sps.uniform.rvs(size=10**3) 
a = np.ones((3, 4))

# print(a.shape, len(a), len(a[0]))
# print(a)

# c = [0]*len(a)
# for i in range(len(a)):
#     print(a[i])
#     print(a[i].cumsum())
#     c[i]=a[i].cumsum()

%time S2 = cumsum(a)



CPU times: user 29 µs, sys: 8 µs, total: 37 µs
Wall time: 40.3 µs


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [19]:
from copy import copy
def np_transformation(x, a=1):
    """  
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются 
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и 
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке, 
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    b = x.copy()
    b[:, 1::2] = a
    b[:, 0::2] = b[:,0::2]**3
    c = b[:, ::-1]
    return np.hstack((x, c))

In [20]:
x = np.array([[i for i in range(1, 13, 2)]])
x.shape = (2,3)
print(x)

b = x.copy()
# b[:, 1::2] = 1
# b[:, 1::2] = 1

print(b[:, ::-1])

# b = x.copy
# b[:, 1::2] = a
# b[:, 0::2] = b[:,0::2]**3
# c = b[:, ::-1]
# np.hstack((x, c))

# %time S2 = np_transformation(x, 5)

[[ 1  3  5]
 [ 7  9 11]]
[[ 5  3  1]
 [11  9  7]]


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [47]:
def np_encode(x):
    """  
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора 
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые 
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор 
    repetitions добавляет длины последовательностей подряд идущих повторений. 
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    # ensure array
    x = np.asanyarray(x)
    if x.ndim != 1:
        raise ValueError('only 1D array supported')
    n = x.shape[0]

    # handle empty array
    if n == 0:
        return np.array([]), np.array([])

    else:
        # find run starts
        loc_run_start = np.empty(n, dtype=bool)
                
        loc_run_start[0] = True

        print(x[:-1])
        print(x[1:])
        
        np.not_equal(x[:-1], x[1:], out=loc_run_start[1:])
        print(loc_run_start)

        run_starts = np.nonzero(loc_run_start)[0]
        print(run_starts)

        # find run values
        run_values = x[loc_run_start]

        # find run lengths
        print(n)
        print(np.append(run_starts, n))
        
        run_lengths = np.diff(np.append(run_starts, n))

        return run_values, run_lengths

In [48]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

# %time x, num = np_encode(X)
print(np_encode(X))

[1 2 2 3 3 1 1 5 5 2 3]
[2 2 3 3 1 1 5 5 2 3 3]
[ True  True False  True False  True False  True False  True  True False]
[ 0  1  3  5  7  9 10]
12
[ 0  1  3  5  7  9 10 12]
(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))
